//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public Nullable<int> customerid { get; set; }
        public string shipaddress { get; set; }
        public string shipnote { get; set; }
        public string status { get; set; }
        public string shipphone { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
