//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int id { get; set; }
        [Display(Name="Tên nhà cung cấp"),Required]
        public string name { get; set; }
[Display(Name="Địa chỉ nhà cung cấp"),Required]
        public string address { get; set; }
        [Display(Name="Số điện thọai sản phẩm"),Required]
        public string phone { get; set; }
        [Required,Display(Name="Email")]
        public string email { get; set; }
        [Display(Name="Trạng thái sản phẩm"),Required]
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
